GET https://jsonplaceholder.typicode.com/posts

###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/application/json
charset: UTF-8
{
  title: "foo",
  body: "bar",
  userId: 1
}
